config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home

  resources :users

  resources :comments

  resources :ideas
  post '/paged' => 'ideas#paged'
  get '/promoted' => 'ideas#get_promoted_ideas'
  post '/promoted/confirmed' => 'ideas#confirm_promotion'

  resources :first_pages, :path => 'idea/first-page'
  resources :page_comments, :path => 'first-page/comments'

  resource :session
  get '/login' => 'sessions#new', :as =>'login'
  get '/logout' => 'sessions#destroy', :as =>'logout'

  resource :likes
  post '/likes-current' => 'likes#check_likes', :as =>'likes-current'
  post '/first-page/likes' => 'likes#like_page' 
  post '/first-page/likes/check' => 'likes#check_page'

  resources :tags, only: [:index, :show]
  get '/tags/:id' => 'tags#show'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, presence: true, uniqueness: true
	validates :password, :length => { :within => 6...20},
						 on: :create

	has_many :ideas
	has_many :comments
	has_many :likes
	has_many :pages
	has_many :page_comments
	has_many :page_likes

	def self.validate_session(id, session)
		if (id != nil && session != nil)
			user = find_by_id(id)
			if (session == user.session_token)
				return true
			else
				return false
			end
		else 
			return false
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include SessionsHelper
	before_filter :check_session_with_redirect

	def show
		@user = get_user()

		# User Content
		@ideas = @user.ideas

		# User Comments
		@comments = @user.comments
		@ideas_from_comments = Array.new
		@comments.each do |comment|
			@ideas_from_comments.push(comment.idea)
		end

		# User Likes
		@likes = @user.likes
		@ideas_from_likes = Array.new
		@likes.each do |like|
			@ideas_from_likes.push(like.idea)
		end
		
	end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class='container-fluid'>
	<div class='row'>
		<section class='user-content'>
			<span>You are</span> <strong><%= @user.email %></strong>
		</section>
	</div>
	<% unless @ideas.empty? %>
		<div class='row'>
			<div class='section-label'><span>Ideas</span></div>
			<section class='user-content'>
				<% @ideas.each do |idea| %>
					<div class='user-idea'>
						<div><%= idea.idea %></div>
						<div>
							<% if idea.isPromoted %>
								<a href='/idea/first-page/<%= idea.promoted_id%>/edit'><i data-toggle="tooltip" title="Promoted" class='glyphicon glyphicon-star pink'></i></a>
								<i data-toggle="tooltip" title="To delete you must delete the promoted page" class='glyphicon glyphicon-trash cursor soft-grey'></i>
							<% end %>
							<% if !idea.isPromoted %>
								<%= link_to raw("<i class='glyphicon glyphicon-trash cursor'></i>"),  idea_path(idea.id), :method => :delete, data: { confirm: "Are you sure?" } %>
							<% end %>
						</div>
					</div>
				<% end %>
			</section>
		</div>
	<% end %>
	<% unless @comments.empty? %>
		<div class='row'>
			<div class='section-label'><span>Comments</span></div>
			<section class='user-content'>
				<% @comments.zip(@ideas_from_comments).each do |comment, idea| %>
					<div class='comment-idea-group'>
						<% unless (idea.nil?) %>
							<div class='comment-item'><%= comment.comment %></div>
							<div class='shortened-idea'><%= idea.idea[0, 200] %>...</div>
						<% end %>
					</div>
				<% end %>
			</section>
		</div>
	<% end %>
	<% unless @likes.empty? %>
		<div class='row'>
			<div class='section-label'><span>Likes</span></div>
			<section class='user-content'>
				<% @likes.zip(@ideas_from_likes).each do |like, idea| %>
					<div class='like-idea-group'>
						<% unless (idea.nil?) %>
							<div class='shortened-idea'><%= idea.idea[0, 200] %>...</div>
						<% end %>
					</div>
				<% end %>
			</section>
		</div>
	<% end %>
</div>