config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home

  resources :users

  resources :comments

  resources :ideas
  post '/paged' => 'ideas#paged'
  get '/promoted' => 'ideas#get_promoted_ideas'
  post '/promoted/confirmed' => 'ideas#confirm_promotion'

  resources :first_pages, :path => 'idea/first-page'
  resources :page_comments, :path => 'first-page/comments'

  resource :session
  get '/login' => 'sessions#new', :as =>'login'
  get '/logout' => 'sessions#destroy', :as =>'logout'

  resource :likes
  post '/likes-current' => 'likes#check_likes', :as =>'likes-current'
  post '/first-page/likes' => 'likes#like_page' 
  post '/first-page/likes/check' => 'likes#check_page'

  resources :tags, only: [:index, :show]
  get '/tags/:id' => 'tags#show'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :idea
	belongs_to :user
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	include ActionView::Helpers::SanitizeHelper

	belongs_to :user
	has_many :comments
	has_many :likes
	has_many :pages
	has_many :tag_instances

	before_save :sanitize_idea, :preserve_linebreaks, :trim_size
	before_destroy :delete_comments

	# Promotion is a one-way gate. Once it's promoted - it is, no undoing
	def promote 
		self.isPromoted = true
		self.save
	end

	def confirmPromotion
		self.promotionConfirmed = true;
		self.save
	end

	def needs_confirmation
		!self.promotionConfirmed && self.isPromoted
	end

	def promoted_id
		if self.isPromoted 
			page = Page.find_by(idea_id: self.id)
			return page.id
		end
		return nil
	end

	def tag(id)
		tag = Tag.find(id)
		instance = tag.tag_instances.create(:idea_id => self.id)
		instance.save
	end

	def get_tags
		return self.tag_instances
	end

	def get_tags_by_name
		tags = self.tag_instances
		tag_names = Array.new
		tags.each do |tag|
			tag_names.push(tag.get_tag_name)
		end
		return tag_names
	end

	def untag(id)
		instance = self.tag_instances.where(tag_id: id)
		instance.destroy
	end

	private 
		def sanitize_idea
			self.idea = strip_tags(self.idea)
			if (self.idea.size > 0) 
				return true
			else 
				return false
			end
		end

		def preserve_linebreaks
			self.idea = idea.gsub(/\n/, '<br/>')
		end

		def trim_size 
			self.idea = self.idea[0, 1600]
		end

		def delete_comments 
			self.comments.destroy_all
			self.tag_instances.destroy_all
			self.likes.destroy_all
			self.pages.destroy_all
		end

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :idea
	belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base

	belongs_to :user
	belongs_to :idea

	has_many :page_comments
	has_many :page_likes

	before_destroy :reset_idea

	def lookup_tags
		origin = self.idea
		tags = origin.get_tags_by_name
		return tags
	end

	private 
		def reset_idea
			unless self.idea.nil?
				self.idea.isPromoted = false;
				self.idea.promotionConfirmed = false;
				self.idea.save
			end

			self.page_comments.destroy_all
			self.page_likes.destroy_all			
		end

end

app/models/page_comment.rb
class PageComment < ActiveRecord::Base
	belongs_to :page
	belongs_to :user
end

app/models/page_like.rb
class PageLike < ActiveRecord::Base
	belongs_to :page
	belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :tag_instances
end

app/models/tag_instance.rb
class TagInstance < ActiveRecord::Base
	belongs_to :idea
	belongs_to :tag

	def get_tag_name
		id = self.tag_id
		return Tag.find(id).tag_name
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, presence: true, uniqueness: true
	validates :password, :length => { :within => 6...20},
						 on: :create

	has_many :ideas
	has_many :comments
	has_many :likes
	has_many :pages
	has_many :page_comments
	has_many :page_likes

	def self.validate_session(id, session)
		if (id != nil && session != nil)
			user = find_by_id(id)
			if (session == user.session_token)
				return true
			else
				return false
			end
		else 
			return false
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end
	
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		tags = Tag.all
  		respond_to do |format|
			format.json  { render :json => tags.to_a }
		end		
	end

	def show		
		id = params[:id]
		unless Tag.where(:id => id).empty?
			tagged_items = TagInstance.where(:tag_id => id)

			@ideas = Array.new
			tagged_items.each do |tag|
				@ideas.push(Idea.find(tag.idea_id))
			end
			@tagName = Tag.find(id).tag_name	
		else 
			redirect_to ideas_path
		end
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/first_pages_helper.rb
module FirstPagesHelper
	include SessionsHelper

	# Controller Level
	def confirm_user_may_enter(id)
		check_session_with_redirect
		user = get_user

		page = user.pages.where(:id => id)
		if page.empty? 
			redirect_to login_path
		end
	end

	# Application Level
	def check_if_has_pages(id)
		user = get_user
		return user.pages
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
	include SessionsHelper

	def compute_score(id)
		score_goal = 10

		idea = Idea.find(id)
		user = get_user

		if idea.user_id != user.id
			comment_count = idea.comments.size
			like_count = idea.likes.size
			total_score = (comment_count / 2) + like_count

			if (total_score >= score_goal)
				idea.promote

				if (user) 
					page = Page.new(user_id: user.id, idea_id: idea.id)
					page.save
				end
			end
		end
	end

	def check_for_new_promotions(id)
		user = User.find(id)
		ideas = user.ideas

		ideas.each do |idea|
			if (idea.needs_confirmation)
				return true
			end
		end
		return false
	end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def check_session_with_redirect
		unless User.validate_session(session[:user_id], session[:session_token])
			flash[:alert] = "Please login."
			redirect_to login_path
		end
	end	

	def check_user_state
		return User.validate_session(session[:user_id], session[:session_token])
	end

	# Keep the user out of things like the login page
	def redirect_valid_user
		if User.validate_session(session[:user_id], session[:session_token])
			redirect_to ideas_path
		end
	end	

	def get_user
		if check_user_state
			return User.find(session[:user_id])
		end
		return false
	end
	
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>You write here | PageWires</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <%= stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Open+Sans:400,700,300', media: 'all' %> -->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
	<body class="<%= @controller %> <%= @action %>">
	<%= render 'shared/header' %>
	<div class='container page' ng-app='pageWires'>

    <%= render 'shared/page_title' %>
		<%= yield %>
    <%= render 'shared/modals' %>

  </div>
</body>
</html>

app/views/shared/_flash_alert.html.erb
<% if flash[:alert] %>
	<p class='bg-danger'><%= flash[:alert] %></p>
<% end %>

app/views/shared/_header.html.erb
<header class='container-fluid main-header'>
	<div class='logo'>
		<% if (@logged_in) %>
			<%= link_to 'Page Wires', ideas_path %>
		<% else %>
			<%= link_to 'Page Wires', root_path %>
		<% end %>
	</div>

	<div class='site-pages clearfix'>
		<div class='site-page-item'>
			<%= link_to raw("
			<i class='glyphicon glyphicon-file'></i>
			Ideas
			"), ideas_path %>
		</div>
		<div class='site-page-item'>
			<%= link_to raw("
			<i class='glyphicon glyphicon-book'></i>
			Pages
			"), first_pages_path %>
		</div>
	</div>

	<% if (@logged_in) %>

		<div class='new-idea-block'>
			<% if (@confirmation_needed) %>
				<button type="button" class="btn btn-default glyphicon glyphicon-heart inverse-button" data-toggle="modal" data-target="#alertPromotionModal"></button>
			<% end %>
			
			<% if @has_pages %>
				<span class="dropdown">
					<button type='button' class='btn btn-default glyphicon glyphicon-pencil' id="dropdownMenuCreate" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
					<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuCreate">
						<li><a data-toggle="modal" data-target="#newIdeaModal" href="">Create New Idea</a></li>
						<li><a data-toggle="modal" data-target="#pagesListModal" href="">Work on First Pages</a></li>
					</ul>					
				</span>	
			<% else %>
				<button type="button" class="btn btn-default glyphicon glyphicon-pencil" data-toggle="modal" data-target="#newIdeaModal"></button>
			<% end %>

			<span class="dropdown">
				<button type='button' class='btn btn-default glyphicon glyphicon-user dropdown-toggle' id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
				<ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
					<li><%= link_to 'Profile', user_path(@user) %></li>
					<li><%= link_to 'Logout', logout_path %></li>
				</ul>					
			</span>
		</div>
	<% end %>

</header>

app/views/shared/_modals.html.erb
<% if @logged_in %>

	<div ng-controller='CreateCommentCtrl'>
		<%= render 'comments/new_comment' %>
	</div>

	<% if @confirmation_needed %>
		<div ng-controller='FirstPagesAlertCtrl'>
			<%= render 'first_pages/alerted_to_promotion' %>
		</div>
	<% end %>

	<% if @has_pages %>
		<div>
			<%= render 'first_pages/user_pages_list' %>
		</div>	
	<% end %>

	<% if !(@controller == 'ideas' && @action == 'index') %>
		<div ng-controller='IdeaCtrl'>
			<%= render 'ideas/new_idea' %>
		</div>
	<% end %>

<% end %>

app/views/shared/_page_title.html.erb
<% unless @pageTitle.empty? %>
  <div class='page-title'><h1><%= @pageTitle %></h1></div>
<% end %>