config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :home

  resources :users

  resources :comments

  resources :ideas
  post '/paged' => 'ideas#paged'
  get '/promoted' => 'ideas#get_promoted_ideas'
  post '/promoted/confirmed' => 'ideas#confirm_promotion'

  resources :first_pages, :path => 'idea/first-page'
  resources :page_comments, :path => 'first-page/comments'

  resource :session
  get '/login' => 'sessions#new', :as =>'login'
  get '/logout' => 'sessions#destroy', :as =>'logout'

  resource :likes
  post '/likes-current' => 'likes#check_likes', :as =>'likes-current'
  post '/first-page/likes' => 'likes#like_page' 
  post '/first-page/likes/check' => 'likes#check_page'

  resources :tags, only: [:index, :show]
  get '/tags/:id' => 'tags#show'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class='clearfix'>
	<div class='home-header'>
		<h1>Page Wires</h1>
	</div>
</div>
<div class='home-body-content'>
	<div class='row'>
		<div class='col-md-4'>

			<div class='process-wrapper'>
				<div class='process-box'>
					<i class='glyphicon glyphicon-pencil'></i>
					Create Ideas
				</div>
				<div class='transition-box glyphicon glyphicon-arrow-down'>

				</div>
				<div class='process-box'>
					<i class='glyphicon glyphicon-thumbs-up'></i>
					Gain Votes
				</div>
				<div class='transition-box glyphicon glyphicon-arrow-down'>

				</div>				
				<div class='process-box'>
					<i class='glyphicon glyphicon-tree-deciduous'></i>
					Grow your Idea
				</div>
				<div class='transition-box glyphicon glyphicon-arrow-down'>

				</div>
				<div class='process-box'>
					<i class='glyphicon glyphicon-comment'></i>
					Get Feedback
				</div>						
				<div class='transition-box glyphicon glyphicon-arrow-down'>

				</div>
				<div class='process-box'>
					<i class='glyphicon glyphicon-book'></i>
					Go from there!
				</div>			
			</div>
	
		</div>	
		<div class='col-md-8'>
			<h4>Page Wires is a place for writers.</h4>
			<h4>The focus is on growing ideas, using the community of fellow writers to help grow ideas.</h4>
			<h4>And then expanding on those ideas with feedback, voting and contests.</h4>
			<div class='button-wrapper'>
				<%= link_to 'Get Started', login_path, class: 'button outline btn nudgeRight-20' %>
				<%= link_to 'Start Reading', ideas_path, class: 'button outline btn' %>
			</div>
		</div>
	</div>

</div>